### PR TITLE
make ewext compileable on old systems UPD: added as feature flag

### PR DESCRIPTION
**Pull request by kcalbxof**
see https://github.com/rust-lang/rust/issues/79609

This patch does make compilation of ewext work on Ubuntu 20.04 with old mingw version, but IT WILL BREAK current CI/CD workflow due to multiple definitions of _Unwind_Resume (understandably so). I am in no way the rust guru, so i though maybe you guys could do something with it, since it will be useful in a long run.

### CODE REVIEW

**Comment by bgkillas** [comment]
isn't this something we should never push? if its not fixed in master its probably more complicated

**Comment by kcalbxof** [comment]
> isn't this something we should never push? if its not fixed in master its probably more complicated

Yes, hence draft pull request. I could make it a separate feature that is toggled via flag while compiling, so that there is possibility to use this patch, but it would not interfere with anything else. If you guys cool with that, i will update this branch & PR with new commit that does that.
